import datetime
import json
import logging
import os
import random
import re
import uuid
from collections import Counter
from copy import deepcopy
from dataclasses import dataclass
from typing import Dict, List, Tuple

import numpy as np
import torch
import torchaudio
from dotenv import load_dotenv
from langchain_core.output_parsers import JsonOutputParser
from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI
from pyannote.audio import Pipeline
from pydub import AudioSegment
from ruaccent import RUAccent
from transformers import AutoModelForSpeechSeq2Seq, AutoProcessor, pipeline

from F5TTS.f5_tts.api import F5TTS
from src.llm_models import PodcastScript, QuestionsResult
from src.rag import LectureRAG
from src.prompts import (
    ABSTRACT_PROMPT,
    CLEAN_PODCAST_PROMPT,
    EMOT_AN_PROMPT,
    MINDMAP_PROMPT,
    PODCAST_INTROS,
    PODCAST_OUTROS,
    PODCAST_PROMPT,
)

STOPWORDS_PATH = "src/stopwords.txt"
logger = logging.getLogger(__name__)
load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), "..", ".env"))

# =============================================================================
# Data Classes
# =============================================================================


@dataclass
class AudioData:
    """Audio file data after preparation."""

    wav_path: str
    waveform: torch.Tensor
    sample_rate: int


@dataclass
class DiarizationResult:
    """Speaker diarization results."""

    diagram: Dict[str, float]  # {lecturer: %, discussion: %, quiet: %}
    labeled_chunks: List[List]  # [[speaker_id, start, end], ...]


@dataclass
class TranscriptionResult:
    """Speech transcription results."""

    chunks: List[List]  # [[speaker, text, (start, end)], ...]
    lecture_text: str


@dataclass
class TextAnalysis:
    """Text analysis results."""

    popular_words_no_stopw: List[Dict]
    popular_words_w_stopw: List[Dict]
    words_per_minute: List[float]
    speed: Dict[int, float]
    transcripted_chunks: List[List]


# =============================================================================
# Utility Functions
# =============================================================================


def clear_gpu_cache() -> None:
    """Clear the GPU cache if CUDA is available."""
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


def latex_to_md(text: str) -> str:
    """Convert LaTeX syntax to Markdown math syntax.

    Args:
        text: Text to convert.

    Returns:
        Converted text with Markdown math delimiters.
    """
    text = re.sub(r"\\\(\s*(.*?)\s*\\\)", r"$\1$", text)
    text = re.sub(r"\\\[\s*(.*?)\s*\\\]", r"$$\1$$", text, flags=re.DOTALL)
    return text


def parse_json(text: str) -> dict:
    """Extract and clean a JSON string generated by an LLM.

    Includes multiple fix steps: unicode normalization, typographic quotes,
    bare keys/values, trailing commas.

    Args:
        text: Raw text containing a JSON object.

    Returns:
        Parsed dict.

    Raises:
        ValueError: If JSON cannot be parsed after all fix attempts.
    """
    text = text.strip()
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1:
        raise ValueError("В тексте не найден JSON-объект (нет {}).")
    text = text[start : end + 1]

    # Remove invisible characters
    text = re.sub(r"[\u0000-\u001F\u007F-\u009F\u00AD\u202f\xa0]", " ", text)

    # Normalize typographic quotes
    text = (
        text.replace("\u201c", '"')
        .replace("\u201d", '"')
        .replace("\u2032", '"')
        .replace("\u2033", '"')
    )

    # Fix bare backslashes
    text = re.sub(r'\\(?!["\\/bfnrtu])', r"\\\\", text)

    # Attempt 1: direct parse
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Attempt 2: fix bare keys/values and single quotes
    def fix_key_value_and_quotes(match):
        key = match.group(1).strip()
        val = match.group(2).strip()
        val = re.sub(r",$", "", val)

        key_fixed = key.replace('"', '\\"')
        if not (key_fixed.startswith('"') and key_fixed.endswith('"')):
            key_fixed = f'"{key_fixed}"'

        if not (val.startswith('"') and val.endswith('"')):
            val = val.replace("'", '"')
            val = val.replace('"', '\\"')
            val = f'"{val}"'
        elif val.startswith("'") and val.endswith("'"):
            val = val[1:-1].replace('"', '\\"').replace("'", '"')
            val = f'"{val}"'

        return f"{key_fixed}: {val}"

    text_fixed = re.sub(
        r'(\w+|"[^"]+"|' + r"'[^']+'" + r")\s*:\s*([^,{}\n]+)",
        fix_key_value_and_quotes,
        text,
        flags=re.DOTALL,
    )

    # Remove trailing commas
    text_fixed = re.sub(r",\s*([}\]])", r"\1", text_fixed)

    try:
        return json.loads(text_fixed)
    except json.JSONDecodeError as e:
        raise ValueError(
            f"Не удалось распарсить JSON после исправлений. "
            f"Ошибка: {e}\nТекст: {text_fixed[:500]}..."
        )


def fill_silence_intervals(
    data: List[Tuple[str, float, float]],
) -> List[List]:
    """Fill intervals when no words were spoken.

    Args:
        data: List of [speaker_id, start, end] tuples.

    Returns:
        Data with silence intervals (speaker_id=3) filled in.
    """
    filled_data = []

    if data[0][1] > 0:
        filled_data.append([3, 0, data[0][1]])
    for i, entry in enumerate(data):
        speaker, start, end = entry
        filled_data.append(entry)

        if i < len(data) - 1:
            next_start = data[i + 1][1]
            if end < next_start:
                filled_data.append([3, end, next_start])
    return filled_data


# =============================================================================
# Processing Functions
# =============================================================================


def prepare_audio(recording_path: str) -> AudioData:
    """Prepare audio file for processing.

    Converts mp3 to wav if necessary and loads the waveform.

    Args:
        recording_path: Path to audio file (mp3 or wav).

    Returns:
        AudioData with wav_path, waveform, and sample_rate.

    Raises:
        FileNotFoundError: If recording_path does not exist.
    """
    if not os.path.exists(recording_path):
        raise FileNotFoundError(f"Audio path {recording_path} does not exist")

    waveform, sample_rate = torchaudio.load(recording_path)

    if ".mp3" in recording_path:
        wav_path = recording_path[: recording_path.find(".")] + ".wav"
        torchaudio.save(wav_path, waveform, sample_rate)
    else:
        wav_path = recording_path

    return AudioData(wav_path=wav_path, waveform=waveform, sample_rate=sample_rate)


def diarize(wav_path: str, diarization_pipeline: Pipeline) -> DiarizationResult:
    """Perform speaker diarization on audio file.

    Args:
        wav_path: Path to wav audio file.
        diarization_pipeline: Pre-loaded pyannote diarization pipeline.

    Returns:
        DiarizationResult with diagram and labeled_chunks.
    """
    clear_gpu_cache()

    diarization = diarization_pipeline(file=wav_path)

    time_allocation = diarization.chart()
    t_lecturer = time_allocation[0][1]
    t_audience = sum([time_allocation[i][1] for i in range(1, len(time_allocation))])
    t_silence = (
        max([segment.end for segment in diarization.itersegments()])
        - t_lecturer
        - t_audience
    )

    timestamps_of_speakers = []
    for segment, _, speaker in diarization.itertracks(yield_label=True):
        timestamps_of_speakers.append(
            [speaker, round(segment.start, 2), round(segment.end, 2)]
        )

    lector_id = time_allocation[0][0]
    for i in range(len(timestamps_of_speakers)):
        if timestamps_of_speakers[i][0] == lector_id:
            timestamps_of_speakers[i][0] = 1
        else:
            timestamps_of_speakers[i][0] = 2

    time_of_events = t_lecturer + t_audience + t_silence

    diagram = {
        "lecturer": t_lecturer / time_of_events * 100.0,
        "discussion": t_audience / time_of_events * 100.0,
        "quiet": t_silence / time_of_events * 100.0,
    }
    labeled_chunks = fill_silence_intervals(timestamps_of_speakers)

    return DiarizationResult(diagram=diagram, labeled_chunks=labeled_chunks)


def transcribe(
    audio: AudioData,
    diarization: DiarizationResult,
    speech_pipe,
    processor,
) -> TranscriptionResult:
    """Transcribe audio using speech recognition.

    Args:
        audio: AudioData with waveform and sample_rate.
        diarization: DiarizationResult with labeled_chunks.
        speech_pipe: Pre-loaded speech recognition pipeline.
        processor: Pre-loaded audio processor.

    Returns:
        TranscriptionResult with chunks and lecture_text.
    """
    clear_gpu_cache()
    chunks = []

    target_sample_rate = processor.feature_extractor.sampling_rate

    for speaker, start, end in diarization.labeled_chunks:
        start_sample = int(start * audio.sample_rate)
        end_sample = int(end * audio.sample_rate)
        fragment = audio.waveform[:, start_sample:end_sample]

        if fragment.shape[0] > 1:
            fragment = fragment.mean(dim=0, keepdim=True)

        fragment = fragment.squeeze(0)
        fragment_np = fragment.numpy()

        if audio.sample_rate != target_sample_rate:
            resampler = torchaudio.transforms.Resample(
                orig_freq=audio.sample_rate, new_freq=target_sample_rate
            )
            fragment_resampled = resampler(fragment.unsqueeze(0))
            fragment_resampled = fragment_resampled.squeeze(0)
            fragment_np = fragment_resampled.numpy()

        text = ""
        if speaker != 3:
            text = speech_pipe(
                inputs=fragment_np,
                generate_kwargs={"language": "russian"},
                return_timestamps=True,
            )["text"]

        if speaker == 3 or text.strip() == "" or text == " Продолжение следует...":
            text = ""
            speaker = 3

        chunks.append([speaker, text.strip(), (start, end)])

    lecture_text = ""
    for _, text, _ in chunks:
        lecture_text += " " + text.strip()
    lecture_text = lecture_text.replace("  ", " ").strip()

    return TranscriptionResult(chunks=chunks, lecture_text=lecture_text)


def analyze_words(
    chunks: List[List], stopwords_path: str = STOPWORDS_PATH
) -> Tuple[List[Dict], List[Dict]]:
    """Analyze word frequency in chunks.

    Args:
        chunks: List of [speaker, text, timestamp] items.
        stopwords_path: Path to stopwords file.

    Returns:
        Tuple of (popular_words_no_stopw, popular_words_w_stopw).
    """
    with open(stopwords_path) as f:
        stopwords = set(f.read().splitlines())

    word_no_stopw = {1: [], 2: []}
    word_w_stopw = {1: [], 2: []}

    for speaker, text, _ in chunks:
        if speaker != 3:
            word_no_stopw[speaker].extend(
                [
                    word
                    for word in text.lower().split()
                    if word not in stopwords and word.isalpha()
                ]
            )
            word_w_stopw[speaker].extend(
                [word for word in text.lower().split() if word.isalpha()]
            )

    word_counts_lector_no_stopw = Counter(word_no_stopw[1])
    word_counts_audience_no_stopw = Counter(word_no_stopw[2])
    popular_words_no_stopw = [
        dict(word_counts_audience_no_stopw.most_common()[:10]),
        dict(word_counts_lector_no_stopw.most_common()[:10]),
    ]

    word_counts_lector_w_stopw = Counter(word_w_stopw[1])
    word_counts_audience_w_stopw = Counter(word_w_stopw[2])
    popular_words_w_stopw = [
        dict(word_counts_audience_w_stopw.most_common()[:10]),
        dict(word_counts_lector_w_stopw.most_common()[:10]),
    ]

    return popular_words_no_stopw, popular_words_w_stopw


def calculate_speech_speed(chunks: List[List]) -> Tuple[List[float], Dict[int, float]]:
    """Calculate speech speed in words per minute.

    Args:
        chunks: List of [speaker, text, timestamp] items.

    Returns:
        Tuple of (words_per_minute_list, speed_dict).
    """
    total_words = 0
    words_per_minute = {}

    for speaker, text, timestamp in chunks:
        if speaker != 3:
            _, end = timestamp
            end = end // 60
            if end not in words_per_minute:
                words_per_minute[end] = 0
            total_words += len(text.split())
            words_per_minute[end] = total_words

    words_list = np.gradient(
        list(words_per_minute.values()), list(words_per_minute.keys())
    ).tolist()

    seconds = [0]
    for _, _, timestamps in chunks:
        start, end = timestamps
        seconds.append(end)
    minutes = sorted(list(set([second // 60 for second in seconds])))
    speed = dict(zip(minutes, words_list))

    return words_list, speed


def format_chunks(chunks: List[List]) -> List[List]:
    """Format chunks for display, merging short silence intervals.

    Args:
        chunks: List of [speaker, text, timestamp] items.

    Returns:
        Formatted chunks with readable timestamps.
    """
    _transcripted_chunks = deepcopy(chunks)
    del_ind = []

    silence_intervals = [i[2][1] - i[2][0] for i in chunks if i[0] == 3]
    if not silence_intervals:
        mean = 0
    else:
        mean = sum(silence_intervals) / len(silence_intervals)

    for i in range(len(_transcripted_chunks)):
        if _transcripted_chunks[i][0] == 3:
            if (
                float(_transcripted_chunks[i][2][1])
                - float(_transcripted_chunks[i][2][0])
                <= mean
            ):
                del_ind.append(i)

    for i in del_ind[::-1]:
        del _transcripted_chunks[i]
        if i < len(_transcripted_chunks) and i > 0:
            if _transcripted_chunks[i - 1][0] == _transcripted_chunks[i][0]:
                _transcripted_chunks[i - 1][1] += _transcripted_chunks[i][1]
                _transcripted_chunks[i - 1][2] = list(_transcripted_chunks[i - 1][2])
                _transcripted_chunks[i - 1][2][1] = _transcripted_chunks[i][2][1]
                del _transcripted_chunks[i]

    for i in range(len(_transcripted_chunks)):
        start, end = _transcripted_chunks[i][2]
        _transcripted_chunks[i][2] = f"{int(start // 60)}:{int(start % 60)}"

    return _transcripted_chunks


def analyze_text(chunks: List[List]) -> TextAnalysis:
    """Perform complete text analysis on chunks.

    Args:
        chunks: List of [speaker, text, timestamp] items.

    Returns:
        TextAnalysis with all text metrics.
    """
    popular_words_no_stopw, popular_words_w_stopw = analyze_words(chunks)
    words_per_minute, speed = calculate_speech_speed(chunks)
    transcripted_chunks = format_chunks(chunks)

    return TextAnalysis(
        popular_words_no_stopw=popular_words_no_stopw,
        popular_words_w_stopw=popular_words_w_stopw,
        words_per_minute=words_per_minute,
        speed=speed,
        transcripted_chunks=transcripted_chunks,
    )


def extract_clean_fragment(chunks: List[List], audio: AudioData) -> str:
    """Extract a clean fragment of lecturer speech for voice cloning.

    Args:
        chunks: List of [speaker, text, timestamp] items.
        audio: AudioData with waveform and sample_rate.

    Returns:
        Path to saved clean audio fragment.
    """
    fragment = None
    for chunk in chunks[10:]:
        if chunk[0] == 1:
            if chunk[2][1] - chunk[2][0] >= 15:
                fragment = chunk
                break

    if fragment is None:
        raise ValueError("No suitable lecturer fragment found for voice cloning")

    start_sample = int(fragment[2][0] * audio.sample_rate)
    end_sample = int(fragment[2][1] * audio.sample_rate)
    segment = audio.waveform[:, start_sample:end_sample]

    output = audio.wav_path[: audio.wav_path.rfind(".")] + "_clean.wav"
    torchaudio.save(output, segment, audio.sample_rate)

    return output


def generate_podcast(
    podcast_text: dict,
    clean_fragment_path: str,
    wav_path: str,
    f5tts: F5TTS,
    accentizer: RUAccent,
) -> str:
    """Generate podcast audio from text.

    Args:
        podcast_text: Dict with part_N keys containing presenter/lector text.
        clean_fragment_path: Path to clean lecturer audio for voice cloning.
        wav_path: Path to original wav file (for cleanup).
        f5tts: Pre-loaded F5TTS model.
        accentizer: Pre-loaded RUAccent accentizer.

    Returns:
        Path to generated podcast mp3 file.
    """
    podcast_text = deepcopy(podcast_text)

    presenter_speech = ""
    lector_speech = ""
    final_audio = np.array([])

    for i in podcast_text.keys():
        for speaker in podcast_text[i].keys():
            if "presenter" in speaker:
                presenter_speech, sr, spec = f5tts.infer(
                    ref_file="utils/podcast_host.wav",
                    ref_text="",
                    gen_text=accentizer.process_all(podcast_text[i]["presenter"])
                    .strip()
                    .lower(),
                    cfg_strength=3,
                    seed=42,
                    nfe_step=64,
                    remove_silence=True,
                    target_rms=0.1,
                    cross_fade_duration=0.15,
                )
            if "lector" in speaker:
                lector_speech, sr, spec = f5tts.infer(
                    ref_file=clean_fragment_path,
                    ref_text="",
                    gen_text=accentizer.process_all(podcast_text[i]["lector"])
                    .strip()
                    .lower(),
                    cfg_strength=2,
                    seed=42,
                    nfe_step=64,
                    remove_silence=True,
                    target_rms=0.1,
                    cross_fade_duration=0.15,
                )
        final_audio = np.concatenate((final_audio, presenter_speech, lector_speech))

    output_file_path = str(uuid.uuid4())

    torchaudio.save(
        output_file_path + ".wav", torch.tensor(final_audio).unsqueeze(0), 24000
    )

    audio_segment = AudioSegment.from_file(output_file_path + ".wav", format="wav")
    audio_segment.export(output_file_path + ".mp3", format="mp3", bitrate="192k")

    # Cleanup
    os.remove(output_file_path + ".wav")
    os.remove(wav_path)
    os.remove(clean_fragment_path)

    clear_gpu_cache()

    return output_file_path + ".mp3"


# =============================================================================
# Main Service Class
# =============================================================================


class LectureAnalyzer:
    """Lecture analysis service.

    Initialize once at service startup, then call process() for each recording.
    Models are loaded once during initialization for efficiency.

    Example:
        analyzer = LectureAnalyzer(pyannote_api_key="...")
        result = analyzer.process("lecture.mp3", "record_123", "group_A")
    """

    def __init__(
        self,
    ):
        """Initialize the analyzer service.

        Loads all ML models once. This should be called once at service startup.

        Args:
            pyannote_api_key: API key for pyannote speaker diarization.
            llm_base_url: Base URL for the LLM API endpoint.
        """
        self.device = "cuda:0" if torch.cuda.is_available() else "cpu"
        self.torch_dtype = torch.float16 if torch.cuda.is_available() else torch.float32

        self.diarization_pipeline = self._load_diarization_pipeline(
            os.getenv("HUGGINGFACEHUB_API_TOKEN")
        )
        self.speech_pipe, self.processor = self._load_whisper()
        self.f5tts, self.accentizer = self._load_tts()

        # LLM with reasoning for all tasks
        self.llm = ChatOpenAI(
            model=os.getenv("LLM_NAME"),
            base_url=os.getenv("LLM_URL"),
            api_key=os.getenv("LLM_API_KEY"),
            reasoning={"effort": "high", "summary": None},
            temperature=0,
        )

        # JSON parsers for structured outputs (works with reasoning mode)
        self.questions_parser = JsonOutputParser(pydantic_object=QuestionsResult)
        self.podcast_parser = JsonOutputParser(pydantic_object=PodcastScript)

        # RAG по умолчанию
        self.rag = LectureRAG()

    def _load_diarization_pipeline(self, api_key: str) -> Pipeline:
        """Load pyannote speaker diarization pipeline."""
        return Pipeline.from_pretrained(
            "pyannote/speaker-diarization-3.1",
            use_auth_token=api_key,
        ).to(torch.device(self.device))

    def _load_whisper(self):
        """Load Whisper speech recognition model."""
        model_id = "openai/whisper-large-v3"
        model = AutoModelForSpeechSeq2Seq.from_pretrained(
            model_id,
            dtype=self.torch_dtype,
            low_cpu_mem_usage=True,
            use_safetensors=True,
        )
        model.to(self.device)

        processor = AutoProcessor.from_pretrained(model_id)
        pipe = pipeline(
            "automatic-speech-recognition",
            model=model,
            tokenizer=processor.tokenizer,
            feature_extractor=processor.feature_extractor,
            dtype=self.torch_dtype,
            device=self.device,
        )
        return pipe, processor

    def _load_tts(self):
        """Load F5TTS and RUAccent for podcast generation."""
        f5tts = F5TTS(
            ckpt_file="F5TTS/ckpts/model_v4.safetensors",
            vocab_file="F5TTS/ckpts/vocab.txt",
            device=self.device,
        )
        accentizer = RUAccent()
        accentizer.load(
            omograph_model_size="turbo3.1", use_dictionary=True, tiny_mode=False
        )
        return f5tts, accentizer

    # =========================================================================
    # LLM Methods (langchain + structured outputs)
    # =========================================================================

    def _extract_llm_response(self, response) -> str:
        """Extract text from LLM response (handles reasoning mode).

        Args:
            response: AIMessage from llm.invoke().

        Returns:
            Extracted text content.
        """
        content = response.content
        if isinstance(content, list):
            for item in reversed(content):
                if isinstance(item, dict) and "text" in item:
                    return item["text"]
            return "".join(
                item.get("text", "") if isinstance(item, dict) else str(item)
                for item in content
            )
        return content

    def _generate_abstract(self, lecture_text: str) -> str:
        """Generate lecture abstract (markdown).

        Args:
            lecture_text: Full lecture transcription.

        Returns:
            Markdown abstract text.
        """
        response = self.llm.invoke(
            f"{ABSTRACT_PROMPT}\n\nТекст лекции:\n{lecture_text}"
        )
        return latex_to_md(self._extract_llm_response(response))

    def _generate_questions(self, lecture_text: str) -> List[str]:
        """Generate self-check questions using structured output with reasoning.

        Args:
            lecture_text: Full lecture transcription.

        Returns:
            List of 10-12 questions.
        """
        questions_prompt = PromptTemplate(
            template="""
Ты — ИИ-методист. Получишь текст лекции и должен составить список вопросов.

Сформируй строго структурированный JSON, соответствующий схеме ниже.

{format_instructions}

Инструкция:
1. Сформулируй ровно 12 вопросов.
2. Следуй порядку изложения лекции.
3. Используй только русский язык.
4. Никаких комментариев, пояснений, разметки.
5. Для оформления формул используй markdown форматирование

Верни строго корректный JSON.
Текст лекции:
{lecture_text}
""",
            input_variables=["lecture_text"],
            partial_variables={
                "format_instructions": self.questions_parser.get_format_instructions()
            },
        )
        try:
            result = self.questions_parser.invoke(
                self.llm.invoke(questions_prompt.format(lecture_text=lecture_text))
            )
            # Extract question strings from Question objects
            questions = result.get("questions", [])
            return [
                q.get("question", q) if isinstance(q, dict) else str(q)
                for q in questions
            ]
        except Exception:
            return []

    def _generate_mindmap(self, lecture_text: str, max_retries: int = 10) -> dict:
        """Generate mind map structure.

        Args:
            lecture_text: Full lecture transcription.
            max_retries: Maximum number of retry attempts.

        Returns:
            Dict with mind map structure.
        """
        for attempt in range(max_retries):
            try:
                response = self.llm.invoke(
                    f"{MINDMAP_PROMPT}\n\nТекст лекции:\n{lecture_text}"
                )
                return parse_json(self._extract_llm_response(response))
            except Exception as e:
                logger.warning(
                    "Mindmap: попытка %d/%d не удалась: %s", attempt + 1, max_retries, e
                )
        logger.error("Не удалось сгенерировать mindmap после %d попыток", max_retries)
        return {"title": "Не удалось сгенерировать", "nodes": []}

    def _analyze_emotion(self, text: str) -> str:
        """Analyze emotional tone of a text fragment.

        Args:
            text: Text fragment to analyze.

        Returns:
            Adjectives describing the fragment.
        """
        response = self.llm.invoke(f"{EMOT_AN_PROMPT}\n\nФрагмент:\n{text}")
        return self._extract_llm_response(response).strip()

    def _generate_podcast_script(
        self, lecture_text: str, questions: List[str], max_retries: int = 10
    ) -> dict:
        """Generate podcast script using structured output with reasoning.

        Args:
            lecture_text: Full lecture transcription.
            questions: List of questions for the podcast.
            max_retries: Maximum number of retry attempts.

        Returns:
            Dict with podcast parts.
        """
        questions_str = "\n".join(f"{i + 1}. {q}" for i, q in enumerate(questions))
        prompt = PromptTemplate(
            template="""{base_prompt}

            {format_instructions}

            Вопросы:
            {questions_str}

            Лекция:
            {lecture_text}""",
            input_variables=["lecture_text", "questions_str"],
            partial_variables={
                "base_prompt": PODCAST_PROMPT,
                "format_instructions": self.podcast_parser.get_format_instructions(),
            },
        )
        for attempt in range(max_retries):
            try:
                response = self.llm.invoke(
                    prompt.invoke(
                        {"lecture_text": lecture_text, "questions_str": questions_str}
                    )
                )
                text = self._extract_llm_response(response)
                return self.podcast_parser.invoke(text)
            except Exception as e:
                logger.warning(
                    "Подкаст: попытка %d/%d не удалась: %s", attempt + 1, max_retries, e
                )
        logger.error("Не удалось сгенерировать подкаст после %d попыток", max_retries)
        return {"parts": []}

    def _clean_podcast_part(self, part: dict) -> dict:
        """Clean a single podcast part for TTS.

        Args:
            part: Dict with presenter and lector text.

        Returns:
            Cleaned podcast part as dict.
        """
        presenter_text = part.get("presenter", "")
        lector_text = part.get("lector", "")

        presenter_response = self.llm.invoke(
            f"{CLEAN_PODCAST_PROMPT}\n\nТекст:\n{presenter_text}"
        )
        cleaned_presenter = self._extract_llm_response(presenter_response)

        lector_response = self.llm.invoke(
            f"{CLEAN_PODCAST_PROMPT}\n\nТекст:\n{lector_text}"
        )
        cleaned_lector = self._extract_llm_response(lector_response)

        return {"presenter": cleaned_presenter, "lector": cleaned_lector}

    def _clean_podcast(self, podcast_script: dict) -> dict:
        """Clean entire podcast script for TTS.

        Args:
            podcast_script: Dict with podcast parts.

        Returns:
            Cleaned podcast script formatted for generate_podcast function.
        """
        cleaned_parts = {}

        intro = random.choice(PODCAST_INTROS)
        cleaned_parts["part_0"] = intro

        for i, part in enumerate(podcast_script.get("parts", [])):
            cleaned_parts[f"part_{i + 1}"] = self._clean_podcast_part(part)

        outro = random.choice(PODCAST_OUTROS)
        cleaned_parts[f"part_{len(podcast_script.get('parts', [])) + 1}"] = outro

        return cleaned_parts

    def process(
        self,
        recording_path: str,
        record_id: str,
        groups: List[str],
        lection_date: datetime.date = None,
        use_rag: bool = True,
    ) -> dict:
        """Process a single lecture recording.

        Args:
            recording_path: Path to audio file (mp3 or wav).
            record_id: Unique identifier for this recording.
            groups: List of student group identifiers.
            lection_date: Date of the lecture (defaults to today).

        Returns:
            Dict with all analysis results.

        Raises:
            FileNotFoundError: If recording_path does not exist.
        """
        if lection_date is None:
            lection_date = datetime.date.today()

        audio = prepare_audio(recording_path)

        diarization_result = diarize(audio.wav_path, self.diarization_pipeline)

        transcription = transcribe(
            audio, diarization_result, self.speech_pipe, self.processor
        )

        text_analysis = analyze_text(transcription.chunks)

        llm_result = self._llm_analyze(transcription.lecture_text)

        clean_fragment_path = extract_clean_fragment(transcription.chunks, audio)
        if llm_result["podcast_text_ok"]:
            podcast_path = generate_podcast(
                llm_result["podcast_text"],
                clean_fragment_path,
                audio.wav_path,
                self.f5tts,
                self.accentizer,
            )
        else:
            podcast_path = None

        clear_gpu_cache()

        if use_rag:
            try:
                self.rag.add_lecture(
                    lecture_text=transcription.lecture_text,
                    student_groups=groups,
                    lecture_date=lection_date,
                    record_id=record_id,
                )
            except Exception as e:
                logger.error("Не удалось добавить лекцию в RAG (record_id=%s): %s", record_id, e)

        return {
            "lecture_text": transcription.lecture_text,
            "abstract_text": llm_result["abstract_text"],
            "speech_speed": text_analysis.speed,
            "mindmap": llm_result["mind_map"],
            "popular_words_no_stopw": text_analysis.popular_words_no_stopw,
            "popular_words_w_stopw": text_analysis.popular_words_w_stopw,
            "conversation_static": diarization_result.diagram,
            "lecture_timeline": text_analysis.transcripted_chunks,
            "questions": llm_result["questions"],
            "podcast": podcast_path,
        }

    def get_results(
        self,
        recording_path: str,
        record_id: str,
        group: str,
        lection_date: datetime.date = None,
    ) -> str:
        """Process recording and return results as JSON string.

        This method provides backward compatibility with the old API.

        Args:
            recording_path: Path to audio file.
            record_id: Unique identifier for this recording.
            group: Student group identifier.
            lection_date: Date of the lecture.

        Returns:
            JSON string with all analysis results.
        """
        result = self.process(recording_path, record_id, [group], lection_date)
        return json.dumps(result, default=str)

    def _llm_analyze(self, lecture_text: str) -> dict:
        """Analyze lecture using LLM with structured outputs.

        Generates abstract, questions, mind map, podcast text.

        Args:
            lecture_text: Full lecture transcription.

        Returns:
            Dict with abstract_text, questions, mind_map, podcast_text.
        """
        abstract_text = self._generate_abstract(lecture_text)

        mind_map = self._generate_mindmap(lecture_text)

        questions = self._generate_questions(lecture_text)

        podcast_script = self._generate_podcast_script(lecture_text, questions)
        podcast_text_ok = len(podcast_script.get("parts", [])) > 0

        podcast_text = self._clean_podcast(podcast_script) if podcast_text_ok else {}

        return {
            "abstract_text": abstract_text,
            "mind_map": mind_map,
            "questions": questions,
            "podcast_text": podcast_text,
            "podcast_text_ok": podcast_text_ok,
        }
